cellInfo = { ...
    { ...
    'CassieInBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'leftLeg', 1, 'Bus: CassieLegInBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    { ...
    'CassieLegInBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'hipRollDrive', 1, 'Bus: ElmoInBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'hipYawDrive', 1, 'Bus: ElmoInBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'hipPitchDrive', 1, 'Bus: ElmoInBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'kneeDrive', 1, 'Bus: ElmoInBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'footDrive', 1, 'Bus: ElmoInBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    { ...
    'ElmoInBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'controlWord', [1 1], 'uint16', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'torque', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    { ...
    'CassieOutBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'pelvis', 1, 'Bus: CassiePelvisOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'leftLeg', 1, 'Bus: CassieLegOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    { ...
    'CassiePelvisOutBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'targetPc', 1, 'Bus: TargetPcOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    { ...
    'TargetPcOutBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'etherCatStatus', [6 1], 'int32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'etherCatNotifications', [21 1], 'int32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'taskExecutionTime', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'overloadCounter', [1 1], 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'cpuTemperature', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    { ...
    'CassieLegOutBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'hipRollDrive', 1, 'Bus: ElmoOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'hipYawDrive', 1, 'Bus: ElmoOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'hipPitchDrive', 1, 'Bus: ElmoOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'kneeDrive', 1, 'Bus: ElmoOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'footDrive', 1, 'Bus: ElmoOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    { ...
    'ElmoOutBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'statusWord', [1 1], 'uint16', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'position', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'velocity', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'torque', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'dcLinkVoltage', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'gearRatio', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    } ...
    };



Simulink.Bus.cellToObject(cellInfo)