function [q_pitch,q_knee] = Cassia_IK_LEG(qLA,qLL)
%CASSIA_IK_LEG
%    [Q_PITCH,Q_KNEE] = CASSIA_IK_LEG(QLA,QLL)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Mar-2020 17:50:44

t2 = qLL.^2;
t3 = sqrt(2.0);
t4 = t2.*8.517375555584707e17;
t5 = t2.^2;
t9 = t5.*8.176497155859972e17;
t6 = t4-t9-3.51270923427573e14;
t7 = sqrt(t6);
t10 = t3.*t7.*2.95066018188323e-10;
t11 = t2.*1.88407;
t8 = t10+t11-9.81307e-1;
t12 = t8.^2;
t13 = -t12+1.0;
t14 = sqrt(t13);
q_pitch = qLA+acos(1.0./sqrt(t2.*9.614390369299999e-1-t14.*1.02199e-1+t3.*t7.*1.50571894015483e-10+2.008501920700003e-2).*(t2.*9.33368278e-1+t14.*6.81e-2+t3.*t7.*1.461757054104952e-10+5.429512199999958e-3));
if nargout > 1
    q_knee = -acos(t8);
end
