function [dLA,dLL] = Cassia_FK_V_LEG(q_pitch,q_knee,dq_pitch,dq_knee)
%CASSIA_FK_V_LEG
%    [DLA,DLL] = CASSIA_FK_V_LEG(Q_PITCH,Q_KNEE,DQ_PITCH,DQ_KNEE)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Mar-2020 18:06:15

t3 = cos(q_knee);
t4 = sin(q_knee);
t2 = t3-t4.*1.37465e-1+9.92267e-1;
t5 = t4.*2.00272e-1;
t6 = t3+t5+1.02067;
t7 = 1.0./t6;
t8 = t3.*5.102989999999999e-1;
t9 = t4.*1.02199e-1;
t10 = t8+t9+5.20845e-1;
t11 = 1.0./sqrt(t10);
dLA = dq_pitch-dq_knee.*t7.*t11.*1.0./sqrt(t2.^2.*t7.*(-4.80936e-1)+1.0).*(t4.*2.59853e-1-cos(q_knee.*2.0).*7.77874e-3+t3.*(t4.*2.54519e-1+1.18731e-1)+1.25486e-1);
if nargout > 1
    dLL = dq_knee.*t11.*(t3.*5.10994e-2-t4.*2.55149e-1);
end
