function [d_pitch,d_knee] = Cassia_IK_V_LEG(qLA,qLL,dLA,dLL)
%CASSIA_IK_V_LEG
%    [D_PITCH,D_KNEE] = CASSIA_IK_V_LEG(QLA,QLL,DLA,DLL)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Mar-2020 18:07:49

d_pitch = dLA;
if nargout > 1
    t2 = qLL.^2;
    t3 = sqrt(2.0);
    t4 = t2.*8.517375555584707e17;
    t5 = t2.^2;
    t6 = t4-t5.*8.176497155859972e17-3.51270923427573e14;
    t7 = t2.*3.644321390338135e25+t3.*sqrt(t6).*5.707406846059895e15-1.898123790829717e25;
    d_knee = dLL.*1.0./sqrt(-t7.^2+3.741444191567111e50).*(qLL.*3.76814-qLL.*t3.*1.0./sqrt(t6).*(t2.*6.387888403015603e15-3.327099826400276e15).*7.553690065621068e-8).*1.934281311383407e25;
end
